# Generated by Django 6.0 on 2026-02-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0003_dealerprofile_delivery_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cylinder_size', models.CharField(choices=[('6kg', '6kg'), ('13kg', '13kg')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_refill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_exchange', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dealers.dealerprofile')),
                ('gas_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.gastype')),
            ],
            options={
                'unique_together': {('dealer', 'gas_type')},
            },
        ),
    ]
