# Generated by Django 6.0 on 2026-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
