# Generated by Django 6.0 on 2026-02-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealerprofile_created_at_dealerprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='delivery_radius',
            field=models.IntegerField(choices=[(5, '5 km'), (7, '7 km'), (10, '10 km')], default=5),
        ),
    ]
