# Generated by Django 6.0 on 2026-02-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cylinder_size',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('refill', 'Refill'), ('exchange', 'Exchange')], default='refill', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='gas_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gas.gastype'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
